version: '3.8'

services:
  biblioteca-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:biblioteca
      - SPRING_H2_CONSOLE_ENABLED=true
      - SCRAPING_AMAZON_TIMEOUT=15000
      - SCRAPING_AMAZON_MAX_RETRIES=3
    networks:
      - biblioteca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  biblioteca-network:
    driver: bridge

volumes:
  biblioteca-data:
    driver: local

# Para executar:
# docker-compose up -d
#
# Para parar:
# docker-compose down
#
# Para rebuild:
# docker-compose up --build
#
# Para ver logs:
# docker-compose logs -f biblioteca-api